export { extensionHost, ExtensionHost } from './extensionHost';
export type {
  ExtensionManifest,
  ExtensionInfo,
  ExtensionPermission,
  ExtensionStatus,
  RecordlyExtensionAPI,
  RecordlyExtensionModule,
  RenderHookPhase,
  RenderHookFn,
  RenderHookContext,
  CursorEffectFn,
  CursorEffectContext,
  ExtensionEventType,
  ExtensionEvent,
  ExtensionSettingsPanel,
  ExtensionSettingField,
  ExtensionContributions,
  ContributedCursorStyle,
  ContributedSound,
  ContributedWallpaper,
  ContributedWebcamFrame,
  ContributedFrame,
  FrameInstance,
  MarketplaceExtension,
  MarketplaceSearchResult,
  MarketplaceReviewStatus,
  ExtensionReview,
} from './types';
